{% set name = "trulens-feedback" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trulens_feedback-{{ version }}.tar.gz
  sha256: 1409491c0cbee5ae163b45022fa11667fbfec2468055eeeb4d873153d0327d4e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 100
  skip: true  # [py<39]

requirements:
  host:
    - python
    - poetry-core
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9.0,<4.0.0
    - trulens-core >=1.0.0,<2.0.0
    - nltk >=3.9.1,<4.0.0
    - pydantic >=2.0.0,<3.0.0
    - numpy >=1.23
    - scikit-learn >=1.3.0,<2.0.0
    - scipy >=1.10.1,<2.0.0

test:
  imports:
    - trulens
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: A TruLens extension package implementing feedback functions for LLM App evaluation.
  description: |
    Create credible and powerful LLM apps, faster. TruLens is a software tool that helps you 
    to objectively measure the quality and effectiveness of your LLM-based applications using feedback functions.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/truera/trulens
  doc_url: https://www.trulens.org/reference/trulens/core/schema/feedback/

extra:
  recipe-maintainers:
    - psteyer
